### ISSUE TITLE
Keep getting download error: Caught javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by jcakstins** [scalacenter/homebrew-bloop#18]
Hi, I tried installing bloop following MacOs instructions on [installation guide](https://scalacenter.github.io/bloop/setup#homebrew) but I keep getting the following error.

```Last 15 lines from /Users/janis.cakstins/Library/Logs/Homebrew/bloop/01.coursier:
Downloading https://github.com/coursier/jvm-index/raw/master/index.json
Downloaded https://github.com/coursier/jvm-index/raw/master/index.json
Exception in thread "main" java.lang.Exception: Error while getting https://github.com/coursier/jvm-index/raw/master/index.json: download error: Caught javax.net.ssl.SSLHandshakeException (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://github.com/coursier/jvm-index/raw/master/index.json
	at coursier.jvm.JvmIndex$.$anonfun$load$5(JvmIndex.scala:147)
	at coursier.jvm.JvmIndex$.$anonfun$load$5$adapted(JvmIndex.scala:145)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:83)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by tgodzik** [comment]
It's probably a leftover of when we installed bloop-jvm by default.
