### ISSUE TITLE
bloop update failure

### ISSUE THREAD

**Issue by SimY4** [scalacenter/homebrew-bloop#22]
trace:

```
➜  ~ brew reinstall bloop   
Warning: Treating bloop as a formula. For the cask, use homebrew/cask/bloop
==> Fetching scalacenter/bloop/bloop
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.5.7/bash-completions
Already downloaded: /Users/asimkin/Library/Caches/Homebrew/downloads/c6289de42ba995c0e23b6dcf4130a72babe117a41d2c1db5b97dc057bd7c1b1e--bash-completions
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.5.7/zsh-completions
Already downloaded: /Users/asimkin/Library/Caches/Homebrew/downloads/eff9524e0436edc42f2f8e597f6ecdfc68e6287f66237004d9398d769bfa14f7--zsh-completions
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.5.7/fish-completions
Already downloaded: /Users/asimkin/Library/Caches/Homebrew/downloads/391807df4053d475fb4d38f8947afa394a700d4f9122b880ef0b3d189c64c250--fish-completions
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.5.7/bloop-coursier.json
Already downloaded: /Users/asimkin/Library/Caches/Homebrew/downloads/21c34ac2c5ff1d452da9e34c0980815774f3925e787970fa79b686b83d1f7feb--bloop-coursier.json
==> Reinstalling scalacenter/bloop/bloop 
==> coursier install --install-dir bin --default-channels=false --channel channel bloop
Last 15 lines from /Users/asimkin/Library/Logs/Homebrew/bloop/01.coursier:
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at coursier.Resolve$.validate(Resolve.scala:365)
	at coursier.Resolve.validate0$1(Resolve.scala:137)
	at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:187)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/scalacenter/homebrew-bloop/issues
```

**Comment by onouguier-ledger** [comment]
Relevant part is IMHO: 

`Downloading https://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/bloopgun_2.12/1.5.7/bloopgun_2.12-1.5.7.pom.sha1
Downloaded https://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/bloopgun_2.12/1.5.7/bloopgun_2.12-1.5.7.pom.sha1
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading ch.epfl.scala:bloopgun_2.12:1.5.7
  not found: https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.12/1.5.7/bloopgun_2.12-1.5.7.pom
  not found: /Users/olivier.nouguier/Library/Caches/Homebrew/java_cache/.ivy2/local/ch.epfl.scala/bloopgun_2.12/1.5.7/ivys/ivy.xml
  not found: https://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/bloopgun_2.12/1.5.7/bloopgun_2.12-1.5.7.pom
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:367)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)`

**Comment by edomiketrotta** [comment]
Having the same issue.

**Comment by edomiketrotta** [comment]
@tgodzik i can see something different now, still not working though:
Error: bloop: SHA256 mismatch
Expected: deb1e65ea9021243e74d292494f0a635f00b082c1ebec59316b76f2f274d48de
  Actual: 836edc551c4f3110440c94b6c88240e084285f4301d8fc61c5b72b4306f6f80e

**Comment by tgodzik** [comment]
That's interesting, it points to the old sha sum, does it get cached? Maybe it can be purged?

**Comment by cheleb** [comment]
Works for me.

**Comment by tgodzik** [comment]
Might be an issue if the sha is changed afterwards without bumping the version :/ If this is a problem for a lot of users I will do another release.

As a workaround you can probably do `brew edit bloop` or `brew edit bloop.rb` and changed the sha to the new one. I think the formula might be downloaded locally, which is why this happened. Sorry about that!

**Comment by edomiketrotta** [comment]
Thanks @tgodzik , I'll give it a try later if it fails with coursier.

**Comment by SimY4** [comment]
Seems to work now
