### ISSUE TITLE
Bloop 2.0 failed to install

### ISSUE THREAD

**Issue by cheleb** [scalacenter/homebrew-bloop#23]
`==> Upgrading scalacenter/bloop/bloop
  1.6.0 -> 2.0.0 
https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.14/scala-library-2.13.14.jar
  100.0% [##########] 5.6 MiB (13.8 MiB / s)
No main class found

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/scalacenter/homebrew-bloop/issues`

**Comment by cheleb** [comment]
Seem to be fixed

**Comment by tgodzik** [comment]
Thanks for reporting! What architecture are you using? Normally this should download a new native image and just run it. Here it looks like it's falling back to JVM, so I might need to fix something there. Are you using M1?

**Comment by tgodzik** [comment]
I will fix it in https://github.com/coursier/apps/pull/241 but homebrew Bloop will need a later update after Bloop 2.0.1 since I need to change coursier.json and that wou;d break sha. I will do the new release soon.

**Comment by cheleb** [comment]
> Thanks for reporting! What architecture are you using? Normally this should download a new native image and just run it. Here it looks like it's falling back to JVM, so I might need to fix something there. Are you using M1?

M1 yes

**Comment by syscl** [comment]
```
==> Upgrading scalacenter/bloop/bloop
  1.6.0 -> 2.0.1
==> coursier install --install-dir bin --default-channels=false --channel channel bloop
Last 15 lines from /Users/syscl/Library/Logs/Homebrew/bloop/01.coursier:
	at coursier.cache.internal.Downloader.download(Downloader.scala:707)
	at coursier.cache.FileCache.download(FileCache.scala:113)
	at coursier.cache.FileCache.filePerPolicy0(FileCache.scala:216)
	at coursier.cache.FileCache.$anonfun$filePerPolicy$5(FileCache.scala:204)
	at coursier.util.EitherT.$anonfun$flatMap$1(EitherT.scala:18)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:51)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/scalacenter/homebrew-bloop/issues

These open issues may also help:
Bloop 2.0 failed to install https://github.com/scalacenter/homebrew-bloop/issues/23
```

My ENV:
macOS Sequoia 15.0
chip: apple silicon M2

**Comment by fmcgough** [comment]
I am also having the same issue, here is the full contents of the log file mentioned above:

<details><summary>Log file</summary>
<p>

```
2024-09-18 14:38:39 +0000

coursier
install
--install-dir
bin
--default-channels=false
--channel
channel
bloop

Picked up _JAVA_OPTIONS: -Duser.home=/Users/frankie/Library/Caches/Homebrew/java_cache
[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala-library/
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala-library/
[2K   98.6% [######### ] 26.9 KiB (86.6 KiB / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala-library/
[2K  100.0% [##########] 27.3 KiB (82.2 KiB / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala-library/maven-metadata.xml
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala-library/maven-metadata.xml
[2K  100.0% [##########] 7.5 KiB (313.4 KiB / s)
[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-library/
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-library/
[2K         [          ] 32.0 KiB (12.5 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-library/
[2K         [          ] 49.5 KiB (18.7 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-library/
[2K         [          ] 69.8 KiB (26.2 KiB / s)
[2A[10000D[2K[1B[2K[1B[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-library/maven-metadata.xml
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-library/maven-metadata.xml
[2K  100.0% [##########] 7.7 KiB (60.8 KiB / s)
[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala-library/maven-metadata.xml.sha1
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2K[1B[2K[1B[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/
[2K    7.2% [          ] 12.1 KiB (637.9 KiB / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/
[2K   46.2% [####      ] 78.0 KiB (1.8 MiB / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/
[2K  100.0% [##########] 168.7 KiB (2.8 MiB / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/maven-metadata.xml
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/maven-metadata.xml
[2K   27.7% [##        ] 16.0 KiB (533.3 KiB / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/maven-metadata.xml
[2K  100.0% [##########] 57.7 KiB (1.1 MiB / s)
[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/
[2K         [          ] 49.5 KiB (348.4 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/
[2K         [          ] 80.0 KiB (487.8 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/
[2K         [          ] 104.7 KiB (469.6 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/
[2K         [          ] 184.7 KiB (763.3 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/
[2K         [          ] 200.7 KiB (760.3 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/
[2K         [          ] 264.7 KiB (819.5 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/
[2K         [          ] 349.4 KiB (1015.7 KiB / s)
[2A[10000D[2K[1B[2K[1B[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/maven-metadata.xml
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/maven-metadata.xml
[2K   29.9% [##        ] 17.2 KiB (113.3 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/maven-metadata.xml
[2K   85.3% [########  ] 49.2 KiB (291.2 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/maven-metadata.xml
[2K  100.0% [##########] 57.7 KiB (306.8 KiB / s)
[2Khttps://oss.sonatype.org/content/repositories/staging/org/scala-lang/scala3-library_3/maven-metadata.xml.sha1
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2K[1B[2K[1B[2A[2Khttps://repo1.maven.org/maven2/
[2K   12.9% [#         ] 16.0 KiB (695.7 KiB / s)
[2Khttps://oss.sonatype.org/content/repositories/staging/
[2K    0.0% [          ] 0B (0B / s)
[2A[2A[10000D[2Khttps://repo1.maven.org/maven2/
[2K   77.6% [#######   ] 96.0 KiB (2.4 MiB / s)
[2Khttps://oss.sonatype.org/content/repositories/staging/
[2K    0.0% [          ] 0B (0B / s)
[2A[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/
[2K    0.0% [          ] 0B (0B / s)
[2Khttps://repo1.maven.org/maven2/ch/
[2K    0.0% [          ] 0B (0B / s)
[2A[2A[10000D[2Khttps://repo1.maven.org/maven2/ch/
[2K    0.0% [          ] 0B (0B / s)
[2K[1B[2K[1B[2A[2A[10000D[2Khttps://repo1.maven.org/maven2/ch/epfl/
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/ch/epfl/scala/
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/ch/epfl/scala/
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/ch/epfl/scala/
[2K  100.0% [##########] 76.3 KiB (615.3 KiB / s)
[2A[10000D[2K[1B[2K[1B[2A[2Khttps://repo1.maven.org/maven2/ch/epfl/scala/bloop-cli_2.13/
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/ch/epfl/scala/bloop-cli_2.13/maven-metadata.xml
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2K[1B[2K[1B[2A[2Khttps://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/bloop-cli_2.13/
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/bloop-cli_2.13/
[2K         [          ] 16.4 KiB (80.3 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/bloop-cli_2.13/maven-metadata.xml
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/bloop-cli_2.13/maven-metadata.xml
[2K  100.0% [##########] 396B (3.5 KiB / s)
[2A[10000D[2Khttps://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/bloop-cli_2.13/maven-metadata.xml
[2K  100.0% [##########] 396B (2.9 KiB / s)
[2Khttps://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/bloop-cli_2.13/maven-metadata.xml.sha1
[2K    0.0% [          ] 0B (0B / s)
[2A[10000D[2K[1B[2K[1B[2A[10000D[2Khttps://repo1.maven.org/maven2/ch/epfl/scala/bloop-cli_2.13/2.0.1/bloop-cli_2.13-2.0.1.pom
[2K  100.0% [##########] 3.8 KiB (202.2 KiB / s)
[2A[10000D[2Khttps://repo1.maven.org/maven2/ch/epfl/scala/bloop-cli_2.13/2.0.1/bloop-cli_2.13-2.0.1.pom
[2K  100.0% [##########] 3.8 KiB (101.1 KiB / s)
[10000DException in thread "main" java.net.MalformedURLException: No protocol found in URL $PREBUILT
	at coursier.paths.CachePath.localFile(CachePath.java:70)
	at coursier.cache.FileCache$.localFile0(FileCache.scala:429)
	at coursier.cache.internal.Downloader.localFile(Downloader.scala:68)
	at coursier.cache.internal.Downloader.downloadUrl(Downloader.scala:625)
	at coursier.cache.internal.Downloader.download(Downloader.scala:707)
	at coursier.cache.FileCache.download(FileCache.scala:113)
	at coursier.cache.FileCache.filePerPolicy0(FileCache.scala:216)
	at coursier.cache.FileCache.$anonfun$filePerPolicy$5(FileCache.scala:204)
	at coursier.util.EitherT.$anonfun$flatMap$1(EitherT.scala:18)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:51)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

HOMEBREW_VERSION: 4.3.23-20-ge220725
ORIGIN: https://github.com/Homebrew/brew
HEAD: e2207258144cafbba38a862c73c23bb538b3de15
Last commit: 6 hours ago
Core tap JSON: 18 Sep 14:36 UTC
Core cask tap JSON: 18 Sep 14:36 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_BOOTSNAP: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Rosetta 2: false

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j10
CMAKE_PREFIX_PATH: /opt/homebrew/opt/readline:/opt/homebrew/opt/sqlite:/opt/homebrew/opt/icu4c:/opt/homebrew/opt/openjdk:/opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /opt/homebrew/opt/python@3.12/Frameworks
PKG_CONFIG_PATH: /opt/homebrew/opt/bash/lib/pkgconfig:/opt/homebrew/opt/libpng/lib/pkgconfig:/opt/homebrew/opt/freetype/lib/pkgconfig:/opt/homebrew/opt/fontconfig/lib/pkgconfig:/opt/homebrew/opt/pcre2/lib/pkgconfig:/opt/homebrew/opt/mpdecimal/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig:/opt/homebrew/opt/readline/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/xz/lib/pkgconfig:/opt/homebrew/opt/python@3.12/lib/pkgconfig:/opt/homebrew/opt/glib/lib/pkgconfig:/opt/homebrew/opt/libxau/lib/pkgconfig:/opt/homebrew/opt/libxdmcp/lib/pkgconfig:/opt/homebrew/opt/libxcb/lib/pkgconfig:/opt/homebrew/opt/libx11/lib/pkgconfig:/opt/homebrew/opt/libxext/lib/pkgconfig:/opt/homebrew/opt/libxrender/lib/pkgconfig:/opt/homebrew/opt/lzo/lib/pkgconfig:/opt/homebrew/opt/pixman/lib/pkgconfig:/opt/homebrew/opt/cairo/lib/pkgconfig:/opt/homebrew/opt/graphite2/lib/pkgconfig:/opt/homebrew/opt/icu4c/lib/pkgconfig:/opt/homebrew/opt/harfbuzz/lib/pkgconfig:/opt/homebrew/opt/jpeg-turbo/lib/pkgconfig:/opt/homebrew/opt/lz4/lib/pkgconfig:/opt/homebrew/opt/zstd/lib/pkgconfig:/opt/homebrew/opt/libtiff/lib/pkgconfig:/opt/homebrew/opt/little-cms2/lib/pkgconfig:/opt/homebrew/opt/bash-completion@2/share/pkgconfig:/opt/homebrew/opt/xorgproto/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/14
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/bash/bin:/opt/homebrew/opt/giflib/bin:/opt/homebrew/opt/libpng/bin:/opt/homebrew/opt/freetype/bin:/opt/homebrew/opt/fontconfig/bin:/opt/homebrew/opt/pcre2/bin:/opt/homebrew/opt/openssl@3/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/xz/bin:/opt/homebrew/opt/python@3.12/bin:/opt/homebrew/opt/gettext/bin:/opt/homebrew/opt/glib/bin:/opt/homebrew/opt/cairo/bin:/opt/homebrew/opt/graphite2/bin:/opt/homebrew/opt/icu4c/bin:/opt/homebrew/opt/harfbuzz/bin:/opt/homebrew/opt/jpeg-turbo/bin:/opt/homebrew/opt/lz4/bin:/opt/homebrew/opt/zstd/bin:/opt/homebrew/opt/libtiff/bin:/opt/homebrew/opt/little-cms2/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/opt/coursier/bin:/opt/homebrew/opt/python@3.12/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin

```

</p>
</details> 

My environment: MacOS Sonoma 14.7, M1 chip

**Comment by tgodzik** [comment]
Ok, I release 2.0.2, which should be finally fixed I hope.

**Comment by syscl** [comment]
thanks for the quick fix @tgodzik , by performing `brew upgrade`, the issue seems to resolved:
```
==> Upgrading scalacenter/bloop/bloop
  1.6.0 -> 2.0.2
==> coursier install --install-dir bin --default-channels=false --channel channel bloop
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/bloop/2.0.2: 8 files, 45MB, built in 9 seconds
==> Running `brew cleanup bloop`...
Removing: /opt/homebrew/Cellar/bloop/1.6.0... (8 files, 20.8MB)
Removing: /Users/syscl/Library/Caches/Homebrew/bloop--2.0.0.json... (349B)
Removing: /Users/syscl/Library/Caches/Homebrew/bloop--2.0.1.json... (304B)
Removing: /Users/syscl/Library/Caches/Homebrew/bloop--bash_completions--2.0.0... (3.0KB)
Removing: /Users/syscl/Library/Caches/Homebrew/bloop--bash_completions--2.0.1... (3.0KB)
Removing: /Users/syscl/Library/Caches/Homebrew/bloop--fish_completions--2.0.0... (3.2KB)
Removing: /Users/syscl/Library/Caches/Homebrew/bloop--fish_completions--2.0.1... (3.3KB)
Removing: /Users/syscl/Library/Caches/Homebrew/bloop--zsh_completions--2.0.0... (2KB)
Removing: /Users/syscl/Library/Caches/Homebrew/bloop--zsh_completions--2.0.1... (2KB)
```

**Comment by tgodzik** [comment]
Thanks for confirming!
