### ISSUE TITLE
Error getting https_proxy.hostname

### ISSUE THREAD

**Issue by entangled90** [scalacenter/homebrew-bloop#6]
This is the log i get from the installation:

```
Downloading Bloop's coursier version, this may take some seconds...
Traceback (most recent call last):
  File "install.py", line 273, in <module>
    coursier_bootstrap(BLOOP_SERVER_TARGET, "bloop.Server")
  File "install.py", line 212, in coursier_bootstrap
    "-Dhttps.proxyHost="+https_proxy.hostname,
TypeError: can only concatenate str (not "NoneType") to str
```
```
$ echo $https_proxy
  localhost:3128
```

**Comment by jvican** [comment]
So, does it fail with the https proxy configuration but it doesn't with the http ?

**Comment by entangled90** [comment]
It fails when the configured proxy does not follow the pattern `http://{hostname}:{port}`.
Previously I had configured as `hostname:port` and I was getting this error.

**Comment by jvican** [comment]
Got it, a fix in this area is very much welcome as I'm not going to have the cycles to look at it soon.

**Comment by entangled90** [comment]
I'll provide a fix for this in the next week. 
Thanks for pointing out where the problem is.
