### ISSUE TITLE
macOS Catalina + brew install fails with Operation not permitted

### ISSUE THREAD

**Issue by matticala** [scalacenter/homebrew-bloop#7]
Hello!

I am trying to install bloop 1.4.0-RC1 but it fails to create cache directories under `/Users/<user>/Library/Caches/`

Initially, it couldn't create the `Coursier/` directory:
```
==> python3 install.py --dest bin --version 1.4.0-RC1
Last 15 lines from /Users/matticala/Library/Logs/Homebrew/bloop/01.python3:
Caused by: java.nio.file.FileSystemException: /Users/matticala/Library/Caches/Coursier: Operation not permitted
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:693)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:800)
	at java.base/java.nio.file.Files.createDirectories(Files.java:786)
	at coursier.bootstrap.launcher.h.a(Unknown Source)
	at coursier.bootstrap.launcher.g.a(Unknown Source)
	... 4 more
Downloading Bloop's coursier version, this may take some seconds...
Coursier couldn't create bin/blp-server. Please report an issue.
Command: ['java', '-jar', 'bin/blp-coursier', 'fetch', 'ch.epfl.scala:bloop-frontend_2.12:1.4.0-RC1', '-r', 'bintray:scalameta/maven', '-r', 'bintray:scalacenter/releases', '-r', 'https://oss.sonatype.org/content/repositories/staging']
Return code: 1
```

so I tried creating it manually, and:

```
==> python3 install.py --dest bin --version 1.4.0-RC1
Last 15 lines from /Users/matticala/Library/Logs/Homebrew/bloop/01.python3:

Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/argonaut-shapeless_6.2_2.12/1.2.0-M11/argonaut-shapeless_6.2_2.12-1.2.0-M11.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Error while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-util_2.12/2.0.0-M9/case-app-util_2.12-2.0.0-M9.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.13.1/okhttp-3.13.1.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Error while downloading https://repo1.maven.org/maven2/io/argonaut/argonaut_2.12/6.2.3/argonaut_2.12-6.2.3.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-bootstrap_2.12/2.0.0-RC3-4/coursier-bootstrap_2.12-2.0.0-RC3-4.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.0.0-RC3-4/coursier-cache_2.12-2.0.0-RC3-4.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/2.0.0-RC3-4/coursier-cli_2.12-2.0.0-RC3-4.jar: /Users/matticala/Library/Caches/Coursier/v1: Operation not permitted, ignoring it
Downloading Bloop's coursier version, this may take some seconds...
Coursier couldn't create bin/blp-server. Please report an issue.
Command: ['java', '-jar', 'bin/blp-coursier', 'fetch', 'ch.epfl.scala:bloop-frontend_2.12:1.4.0-RC1', '-r', 'bintray:scalameta/maven', '-r', 'bintray:scalacenter/releases', '-r', 'https://oss.sonatype.org/content/repositories/staging']
Return code: 255
```

I am using AdoptOpenjdk 13 OpenJ9. Might it be that?

**Comment by matticala** [comment]
As I imagined, it's not Java version because the issue persists with 1.8 and 11

**Comment by jvican** [comment]
Hi @matticala, we don't support AdoptOpenJDK 13 Open J9. We only support Java 8 or Java 11.
  
That being said, the issue seems to come from Coursier. Coursier is likely not supporting anything above JDK 11 either.

**Comment by matticala** [comment]
Hi @jvican, thank you for your reply. As mentioned, I tried with Java 8, 11 and 13: the issue is always the same.

```
❯ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20191101_372 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc1
JCL      - 3504dff40aa based on jdk8u232-b09)

~ 
❯ brew install scalacenter/bloop/bloop
==> Installing bloop from scalacenter/bloop
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.4.0-RC1/install.py
Already downloaded: /Users/matticala/Library/Caches/Homebrew/downloads/6721a6fdcdb62646fe3215acd2bd337d1c73028561f8e056f8d75d24cd0ea5cf--install.py
==> python3 install.py --dest bin --version 1.4.0-RC1
Last 15 lines from /Users/matticala/Library/Logs/Homebrew/bloop/01.python3:
Caused by: java.nio.file.FileSystemException: /Users/matticala/Library/Caches/Coursier: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at coursier.bootstrap.launcher.h.a(Unknown Source)
	at coursier.bootstrap.launcher.g.a(Unknown Source)
	... 4 more
Downloading Bloop's coursier version, this may take some seconds...
Coursier couldn't create bin/blp-server. Please report an issue.
Command: ['java', '-jar', 'bin/blp-coursier', 'fetch', 'ch.epfl.scala:bloop-frontend_2.12:1.4.0-RC1', '-r', 'bintray:scalameta/maven', '-r', 'bintray:scalacenter/releases', '-r', 'https://oss.sonatype.org/content/repositories/staging']
Return code: 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/scalacenter/homebrew-bloop/issues
```

I tried uninstalling java from brew and reinstalling with sdkman, same result.

**Comment by jvican** [comment]
Looks like a permission issue unrelated to Bloop and Java. If this permission issue exists in `/Caches` it might also exist elsewhere and cause the coursier error...
  
Could you download the `install.py` manually with the curl instructions in the website and see what happens when you run it? That should allow you to tinker with the installation script or see where coursier is falling apart.

**Comment by jvican** [comment]
Closing, let's reopen if there's a follow up.
