### ISSUE TITLE
Error during coursier install (1.4.0)

### ISSUE THREAD

**Issue by pierrcou** [scalacenter/homebrew-bloop#9]
Hi,

I tried installing bloop 1.4.0 but I get the following error :

```
~ ❯❯❯ brew install bloop

==> Installing bloop from scalacenter/bloop
==> Installing dependencies for scalacenter/bloop/bloop: coursier/formulas/coursier
==> Installing scalacenter/bloop/bloop dependency: coursier/formulas/coursier
==> Downloading https://github.com/coursier/coursier/releases/download/v2.0.0-RC6-15/cs-x86_64-appl
Already downloaded: /Users/pcou344/Library/Caches/Homebrew/downloads/c193e3dcf367a261d792af05be664892cfdad998dca51f3ee58c7fd3aec179be--cs-x86_64-apple-darwin
==> Downloading https://github.com/coursier/coursier/releases/download/v2.0.0-RC6-15/coursier
Already downloaded: /Users/pcou344/Library/Caches/Homebrew/downloads/a3d385d36c184491d0f0bdb8d69a9653fa2e3c508305e1484e7b5dcac2be05ce--coursier
🍺  /usr/local/Cellar/coursier/2.0.0-RC6-15: 4 files, 50.3MB, built in 4 seconds
==> Installing scalacenter/bloop/bloop
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.4.0/bloop-coursier.json
Already downloaded: /Users/pcou344/Library/Caches/Homebrew/downloads/4225694dfdb5fcb5cc2e021de1536509547a287c1f0f599dd1e9e8e138126e1b--bloop-coursier.json
==> coursier install --install-dir bin --default-channels=false --channel channel bloop -J-Divy.hom
Last 15 lines from /Users/pcou344/Library/Logs/Homebrew/bloop/01.coursier:
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at coursier.Resolve$.validate(Resolve.scala:323)
	at coursier.Resolve.validate0$1(Resolve.scala:112)
	at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:156)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/scalacenter/homebrew-bloop/issues
```

**Comment by jvican** [comment]
Thanks, this happened because Sonatype has been slow in processing this release, should work now!
